# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  pool: 5
  username: markbubien
  password: 
  encoding: unicode

development:
  <<: *default
  database: business_utility_development

test:
  <<: *default
  database: business_utility_test

production:
  <<: *default
  database: business_utility_production

